# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-03 17:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=(django.core.validators.RegexValidator('^[+]?\\d{9,15}$', message='Invalid number'),)),
        ),
    ]
