# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 17:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='users', max_length=30, validators=(django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', message='Tên không được chứa các kí tự đặc biệt'),)),
        ),
    ]
