# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_address',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
