# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_email_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email_address',
            new_name='email',
        ),
    ]
