# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
