# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 03:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161012_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='users', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=(django.core.validators.RegexValidator('^[+]?\\d{9,15}$', message='Số điện thoại không hợp lệ'),)),
        ),
    ]
