# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-04 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161204_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_chef',
            new_name='is_shop',
        ),
    ]
