# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161010_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allergy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
