# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_link',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
