# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160923_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='point',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
