# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default='', max_length=1),
        ),
    ]
