# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20160924_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
    ]
