# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20160924_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
    ]
