# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userprofile_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_link',
            field=models.URLField(null=True),
        ),
    ]
