# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_userprofile_avatar_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_link',
            field=models.URLField(default=''),
        ),
    ]
