# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20161003_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/images/default-avatar.png', null=True, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
