# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
