# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 06:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20161001_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='post',
            new_name='item',
        ),
    ]
