# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20161001_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ingredient',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='in_stock',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
