# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        ('users', '0003_auto_20161013_1017'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set([('item', 'reviewer')]),
        ),
    ]
