# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=30, null=True)),
                ('receiver', models.CharField(max_length=30, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.IntegerField(default=0)),
                ('shipping', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PR', 'Processing'), ('CO', 'Cooking'), ('DE', 'Delivering'), ('FI', 'Finished'), ('CA', 'Canceled')], default='PR', max_length=2)),
                ('phone', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('city', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('ward', models.CharField(blank=True, max_length=30, null=True)),
                ('userprofile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='itemorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.Order'),
        ),
    ]
