# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiver',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
