# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PR', 'Processing'), ('CO', 'Cooking'), ('DE', 'Delivering'), ('FI', 'Finished'), ('CA', 'Canceled')], default='PR', max_length=2),
        ),
    ]
