# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorder',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
