# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_itemorder_is_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ward',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
