# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20161022_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
